# Opens up all sets of duplicate SDSS ID galaxies for GZ: Quench 
# in browser window. All pairs of galaxies have the same images
# with the exception of AGS00004cy and AGS00004n1.

open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001u8
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004cv
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001nc
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004c5
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000009s
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004mc
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001je
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004c3
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00000yl
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004ho
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001k4
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004gs
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001hg
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002w0
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000026z
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003w2
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000010e
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003b8
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000027k
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002wy
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00000kg
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003tr
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000019f
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003c2
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001qr
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS0000449
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001k6
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003ll
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000025r
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003h9
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000020j
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002p1
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001ci
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003tg
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001dp
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002xx
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000020x
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003tu
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS0000236
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002z3
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000012x
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002qc
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS0000233
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003dj
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004cy
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00004n1
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001v8
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003is
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002aw
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003xd
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS0000215
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003wr
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00001sa
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002v5
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS0000294
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003xw
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS000013g
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00003e3
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00000hz
open http://quenchtalk.galaxyzoo.org/#/subjects/AGS00002i4
